### ISSUE TITLE
[BUG]: Totally overwrites existing conf file - no way to return

### ISSUE THREAD

**Issue by Shr4pNull** [2KAbhishek/refind-dark#1]
### Description of the bug

All my settings were lost. I've had to learn about and manually change the new dark settings conf file (which didn't work out of the box for me) just to get it to work. Surely there is a better

At the very least, you should backup and timestamp the previous refind.conf file first before overwriting it all with a single line. 

Surely there is a way to copy the existing settings and then add your dark banners etc so it is extremely close to the working, pre-existing version.

My monitors are not 1080p, so your script failed initially for me. It was simple enough to fix, but how a new linux user just wouldn't be able to do it? Somebody from Windows wouldn't have a clue.
I still can't get it to work the way it was working before applying your script, there is no option to hide any of the boot options. 

Perhaps an uninstall.sh or restoreToPreviousSettings.sh script would be a good idea?

I like the look of your dark theme and the banners and icons etc. Just a little bit more polish in the QOL things would make it impressive. 

### Steps To Reproduce

Run setup.sh

**Comment by 2KAbhishek** [comment]
Thanks for raising the issue, I'll add something that resolves this
