### ISSUE TITLE
[BUG]: script doesn't detect when ESP is not at /boot/efi

### ISSUE THREAD

**Issue by amyipdev** [2KAbhishek/refind-dark#2]
### Description of the bug

Systems that have their ESP at /boot instead of /boot/efi will not be able to use the automatic install script unless the user goes in and changes all occurrences of `/boot/efi` to `/boot`.

### Steps To Reproduce

1. Set up an Arch system with an ESP at /boot
2. Attempt to run script
3. Observe failure

### Additional Information

Alternative option instead of autodetection: allow users to pass an optional command-line target to their ESP

**Comment by 2KAbhishek** [comment]
Thanks for putting up the detailed bug @amyipdev 
I'll add a fix for it when I get some time

I'm more than happy to merge a PR if you are interested in the fix!

I liked your command line argument approach

**Comment by amyipdev** [comment]
I'll send in a PR - I just moved my system to Arch so it might be a bit.

**Comment by 2KAbhishek** [comment]
Thanks, looking forward to it!

**Comment by amyipdev** [comment]
Scheduling this on my calendar for tomorrow - hoping to be able to get the PR out then!

**Comment by 2KAbhishek** [comment]
Thanks for being on top of this @amyipdev!
