### ISSUE TITLE
[BUG]: completely erases refind.conf

### ISSUE THREAD

**Issue by SkyLLerGithub** [2KAbhishek/refind-dark#5]
### Description of the bug

The setup.sh deletes refind.conf entirely... And now I can't load into refind because of this. I have no idea what to do now, please fix your setup script.

### Steps To Reproduce

run ./setup.sh

### Additional Information

Make it so that it only adds the needed line into the config.

**Comment by 2KAbhishek** [comment]
What command did you run for this?
Can you also share more details about your system

**Comment by SkyLLerGithub** [comment]
> What command did you run for this? Can you also share more details about your system

I'm dual booting windows 11 with PopOS

I ran ESP=/mnt (I have mounted my EFI directory) ./setup.sh

**Comment by SkyLLerGithub** [comment]
> What command did you run for this? Can you also share more details about your system

If you meant "system" as in hardware I'm just using a plain Dell laptop for this, other themes work fine.
Also when manually installing it seems that your theme is broken? It just never loads and loads a blank white screen

**Comment by 2KAbhishek** [comment]
Hmm, I don't think /mnt was the correct path for ESP, it should point to the parent directory of EFI/refind.

I'd recommend trying without specifying an ESP or if you still face issues, manually copy the icons and edit the configs

**Comment by SkyLLerGithub** [comment]
> Hmm, I don't think /mnt was the correct path for ESP, it should point to the parent directory of EFI/refind.
> 
> I'd recommend trying without specifying an ESP or if you still face issues, manually copy the icons and edit the configs

I did mount my EFI 
For example:
mount /dev/sda5 /mnt
For refind directory it should be /dev/sda5/EFI/refind, whenever I try to do ESP=/mnt/EFI/refind it'll show up as an duplicate (dev/sda5/EFI/refind/EFI/refind: no such file or directory)

**Comment by 2KAbhishek** [comment]
I haven't explored EFI paths at the /mnt level

Your best bet will be to run the script commands manually at this point, if you know a fix feel free to open a PR

**Comment by SpotlessParty4** [comment]
I think we can add the `-a` parameter to the `tee` command on line 24 of `setup.sh`: `echo "include refind2k/refind2k.conf" | sudo tee "$ESP/EFI/refind/refind.conf"`. Currently, `tee` without `-a` overwrites the file, but we should append to it instead.

**Comment by 2KAbhishek** [comment]
@SpotlessParty4 that sounds like a good suggestion, will be great if you can open up a PR for it 🙏🏽
